---
# tasks file for RHEL7-CIS
- name: Check OS version and family
  fail:
      msg: "This role can only be run against RHEL 7 and CentOS 7. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when:
      - ansible_os_family == 'RedHat'
      - ansible_distribution_major_version | version_compare('7', '!=')
  tags:
      - always

- name: Check ansible version
  fail:
      msg: You must use ansible 2.1 or greater
  when: not ansible_version.full | version_compare('2.1', '>=')
  tags:
      - always

- include: prelim.yml
  become: yes
  tags:
      - prelim_tasks
      - always

- include: level1.yml
  become: yes
  when: cis_control_level1
  tags:
      - cis_control_level1

- include: level2.yml
  become: yes
  when: cis_control_level2
  tags:
      - cis_control_level2


